<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container24VQjx5\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container24VQjx5/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container24VQjx5.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container24VQjx5\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container24VQjx5\appAppKernelProdContainer([
    'container.build_hash' => '24VQjx5',
    'container.build_id' => '2531c079',
    'container.build_time' => 1680173954,
], __DIR__.\DIRECTORY_SEPARATOR.'Container24VQjx5');
