<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Command\CheckTranslationDuplicatesCommand' shared service.

return $this->services['PrestaShopBundle\\Command\\CheckTranslationDuplicatesCommand'] = new \PrestaShopBundle\Command\CheckTranslationDuplicatesCommand(($this->services['translator'] ?? $this->getTranslatorService()));
