<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.prestashop.security.voter.product' shared service.

return $this->privates['debug.security.voter.prestashop.security.voter.product'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \PrestaShopBundle\Security\Voter\PageVoter(), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
