<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.product.attachment' shared service.

return $this->services['form.type.product.attachment'] = new \PrestaShopBundle\Form\Admin\Product\ProductAttachement(($this->services['translator'] ?? $this->getTranslatorService()));
