<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Command\ListCommandsAndQueriesCommand' shared service.

return $this->services['PrestaShopBundle\\Command\\ListCommandsAndQueriesCommand'] = new \PrestaShopBundle\Command\ListCommandsAndQueriesCommand(($this->services['prestashop.core.provider.command_definition_provider'] ?? ($this->services['prestashop.core.provider.command_definition_provider'] = new \PrestaShop\PrestaShop\Core\CommandBus\Parser\CommandDefinitionParser())), $this->parameters['prestashop.commands_and_queries']);
