<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.addon.theme.theme_validator' shared service.

return $this->services['prestashop.core.addon.theme.theme_validator'] = new \PrestaShop\PrestaShop\Core\Addon\Theme\ThemeValidator(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())));
