<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.preferences.configuration' shared service.

return $this->services['prestashop.adapter.preferences.configuration'] = new \PrestaShop\PrestaShop\Adapter\Preferences\PreferencesConfiguration(($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.core.admin.feature_flag.repository'] ?? $this->load('getPrestashop_Core_Admin_FeatureFlag_RepositoryService.php')));
