<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.shop.url.help_provider' shared service.

return $this->services['prestashop.adapter.shop.url.help_provider'] = new \PrestaShop\PrestaShop\Adapter\Shop\Url\HelpProvider(($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService()), ($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')), ($this->services['prestashop.core.help.documentation'] ?? $this->load('getPrestashop_Core_Help_DocumentationService.php')));
