<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.query_handler.get_packed_products_handler' shared service.

return $this->services['prestashop.adapter.product.query_handler.get_packed_products_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Pack\QueryHandler\GetPackedProductsHandler(($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->language->id, ($this->services['prestashop.adapter.product.pack.repository.product_pack_repository'] ?? $this->load('getPrestashop_Adapter_Product_Pack_Repository_ProductPackRepositoryService.php')), ($this->services['prestashop.adapter.attribute.repository.attribute_repository'] ?? $this->load('getPrestashop_Adapter_Attribute_Repository_AttributeRepositoryService.php')), ($this->services['prestashop.core.product.combination.name_builder.combination_name_builder'] ?? $this->load('getPrestashop_Core_Product_Combination_NameBuilder_CombinationNameBuilderService.php')), ($this->services['prestashop.adapter.product.image.repository.product_image_repository'] ?? $this->load('getPrestashop_Adapter_Product_Image_Repository_ProductImageRepositoryService.php')), ($this->services['translator'] ?? $this->getTranslatorService()));
