<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bridge.helper.listing.filters_processor' shared service.

return $this->services['prestashop.bridge.helper.listing.filters_processor'] = new \PrestaShopBundle\Bridge\Helper\Listing\FiltersProcessor(($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService()), ($this->services['prestashop.hook.dispatcher'] ?? $this->getPrestashop_Hook_DispatcherService()));
