<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command_handler.update_products_positions_handler' shared service.

return $this->services['prestashop.adapter.product.command_handler.update_products_positions_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\UpdateProductsPositionsHandler(($this->services['prestashop.core.grid.product.position_definition'] ?? $this->load('getPrestashop_Core_Grid_Product_PositionDefinitionService.php')), ($this->services['prestashop.core.grid.position.position_update_factory'] ?? $this->load('getPrestashop_Core_Grid_Position_PositionUpdateFactoryService.php')), ($this->services['prestashop.core.grid.position.doctrine_grid_position_updater'] ?? $this->load('getPrestashop_Core_Grid_Position_DoctrineGridPositionUpdaterService.php')));
