<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.feature.command_handler.add_feature_handler' shared service.

return $this->services['prestashop.adapter.feature.command_handler.add_feature_handler'] = new \PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\AddFeatureHandler();
