<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.customer.repository.customer_repository' shared service.

return $this->services['prestashop.adapter.customer.repository.customer_repository'] = new \PrestaShop\PrestaShop\Adapter\Customer\Repository\CustomerRepository();
