<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.order_detail.updater' shared service.

return $this->services['prestashop.adapter.order.order_detail.updater'] = new \PrestaShop\PrestaShop\Adapter\Order\OrderDetailUpdater(($this->services['prestashop.adapter.context_state_manager'] ?? $this->load('getPrestashop_Adapter_ContextStateManagerService.php')), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())));
