<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.attachment.query_handler.search_attachment_handler' shared service.

return $this->services['prestashop.adapter.attachment.query_handler.search_attachment_handler'] = new \PrestaShop\PrestaShop\Adapter\Attachment\QueryHandler\SearchAttachmentHandler(($this->services['prestashop.adapter.attachment.attachment_repository'] ?? $this->load('getPrestashop_Adapter_Attachment_AttachmentRepositoryService.php')));
