<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.data.factory.outstanding_decorator' shared service.

return $this->services['prestashop.core.grid.data.factory.outstanding_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\OutstandingGridDataFactory(($this->services['prestashop.core.grid.data.factory.outstanding'] ?? $this->load('getPrestashop_Core_Grid_Data_Factory_OutstandingService.php')), ($this->services['prestashop.core.localization.locale.repository'] ?? $this->getPrestashop_Core_Localization_Locale_RepositoryService()), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->language->getLocale());
