<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bridge.helper.listing.helper_bridge.helper_list_bridge' shared service.

return $this->services['prestashop.bridge.helper.listing.helper_bridge.helper_list_bridge'] = new \PrestaShopBundle\Bridge\Helper\Listing\HelperBridge\HelperListBridge(($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService()), ($this->services['prestashop.user_provider'] ?? $this->load('getPrestashop_UserProviderService.php')), ($this->services['prestashop.bridge.helper.listing.helper_list_configurator'] ?? $this->load('getPrestashop_Bridge_Helper_Listing_HelperListConfiguratorService.php')), ($this->services['prestashop.hook.dispatcher'] ?? $this->getPrestashop_Hook_DispatcherService()), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())));
