<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Command\UpdateLicensesCommand' shared service.

return $this->services['PrestaShopBundle\\Command\\UpdateLicensesCommand'] = new \PrestaShopBundle\Command\UpdateLicensesCommand();
