<?php
$CONFIG = array (
  'instanceid' => 'ocht9bxbw3ps',
  'passwordsalt' => 'MeEVGr8P+cQTqHEGZLnqqJfEPddXok',
  'secret' => '7qBPnup18DM09E1rPe5d7eU+FckBLIfjvd6cNZyq5ELvjaRk',
  'trusted_domains' => 
  array (
    0 => 'muizenmesh.co.za',
  ),
  'datadirectory' => '/home/sexthera/nexcloudata',
  'dbtype' => 'mysql',
  'version' => '22.0.0.11',
  'overwrite.cli.url' => 'https://muizenmesh.co.za/cloud',
  'dbname' => 'sexthera_nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'sexthera_nextcloud',
  'dbpassword' => 'j(M+[GudCu(]',
  'installed' => true,
  'mail_domain' => 'muizenmesh.co.za',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'admin',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.muizenmesh.co.za',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'admin@muizenmesh.co.za',
  'mail_smtppassword' => '#]jmr=d$k,rO',
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);
