<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.shop.traffic_seo.meta.set_up_url' shared service.

return $this->services['form.type.shop.traffic_seo.meta.set_up_url'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\TrafficSeo\Meta\SetUpUrlType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getLanguages(), ($this->services['prestashop.core.form.choice_provider.canonical_redirect_type'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_CanonicalRedirectTypeService.php'))->getChoices(), ($this->services['prestashop.core.util.url.url_file_checker'] ?? $this->load('getPrestashop_Core_Util_Url_UrlFileCheckerService.php'))->isHtaccessFileWritable(), ($this->services['prestashop.adapter.tools'] ?? ($this->services['prestashop.adapter.tools'] = new \PrestaShop\PrestaShop\Adapter\Tools()))->isModRewriteActive(), ($this->services['prestashop.adapter.shop.shop_url'] ?? $this->load('getPrestashop_Adapter_Shop_ShopUrlService.php'))->doesMainShopUrlExist());
