<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.pack.repository.product_pack_repository' shared service.

return $this->services['prestashop.adapter.product.pack.repository.product_pack_repository'] = new \PrestaShop\PrestaShop\Adapter\Product\Pack\Repository\ProductPackRepository(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'ps_');
