<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.form.choice_provider.feature_values_choice_provider' shared service.

return $this->services['prestashop.adapter.form.choice_provider.feature_values_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\FeatureValuesChoiceProvider(($this->services['prestashop.adapter.feature.repository.feature_value_repository'] ?? $this->load('getPrestashop_Adapter_Feature_Repository_FeatureValueRepositoryService.php')), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService()), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->getInt("PS_LANG_DEFAULT"));
