<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.mail_template.variables_builder' shared service.

return $this->services['prestashop.core.mail_template.variables_builder'] = new \PrestaShop\PrestaShop\Core\MailTemplate\Layout\LayoutVariablesBuilder(($this->services['prestashop.core.hook.dispatcher'] ?? $this->getPrestashop_Core_Hook_DispatcherService()), ($this->services['prestashop.core.language.language_default_fonts_catalog'] ?? ($this->services['prestashop.core.language.language_default_fonts_catalog'] = new \PrestaShop\PrestaShop\Core\Language\LanguageDefaultFontsCatalog(['fa' => 'Tahoma', 'ar' => 'Tahoma']))), ['mailThemesUrl' => ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getMailThemesUrl()]);
