<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.updater.product_tag_updater' shared service.

return $this->services['prestashop.adapter.product.updater.product_tag_updater'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\ProductTagUpdater(($this->services['prestashop.adapter.product.repository.tag_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_TagRepositoryService.php')), ($this->services['prestashop.adapter.product.update.product_indexation_updater'] ?? $this->load('getPrestashop_Adapter_Product_Update_ProductIndexationUpdaterService.php')));
