<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.link_block.form_type' shared service.

return $this->services['prestashop.module.link_block.form_type'] = new \PrestaShop\Module\LinkList\Form\Type\LinkBlockType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getLanguages(), ($this->services['prestashop.module.link_block.choice_provider.hook'] ?? $this->load('getPrestashop_Module_LinkBlock_ChoiceProvider_HookService.php'))->getChoices(), ($this->services['prestashop.module.link_block.choice_provider.cms_page'] ?? $this->load('getPrestashop_Module_LinkBlock_ChoiceProvider_CmsPageService.php'))->getChoices(), ($this->services['prestashop.module.link_block.choice_provider.product_page'] ?? $this->load('getPrestashop_Module_LinkBlock_ChoiceProvider_ProductPageService.php'))->getChoices(), ($this->services['prestashop.module.link_block.choice_provider.static_page'] ?? $this->load('getPrestashop_Module_LinkBlock_ChoiceProvider_StaticPageService.php'))->getChoices(), ($this->services['prestashop.module.link_block.choice_provider.category'] ?? $this->load('getPrestashop_Module_LinkBlock_ChoiceProvider_CategoryService.php'))->getChoices(), ($this->services['prestashop.adapter.feature.multistore'] ?? $this->load('getPrestashop_Adapter_Feature_MultistoreService.php'))->isUsed());
