<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.stock.query_handler.get_product_stock_movement_handler' shared service.

return $this->services['prestashop.adapter.product.stock.query_handler.get_product_stock_movement_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Stock\QueryHandler\GetEmployeesStockMovementsHandler(($this->services['prestashop.adapter.product.stock.repository.stock_available_multi_shop_repository'] ?? $this->load('getPrestashop_Adapter_Product_Stock_Repository_StockAvailableMultiShopRepositoryService.php')), ($this->services['prestashop.adapter.product.stock.repository.stock_movement_repository'] ?? $this->load('getPrestashop_Adapter_Product_Stock_Repository_StockMovementRepositoryService.php')));
