<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.update.combination_deleter' shared service.

return $this->services['prestashop.adapter.product.combination.update.combination_deleter'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\Update\CombinationDeleter(($this->services['prestashop.adapter.product.repository.product_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')), ($this->services['prestashop.adapter.product.combination.repository.combination_repository'] ?? $this->load('getPrestashop_Adapter_Product_Combination_Repository_CombinationRepositoryService.php')), ($this->services['prestashop.adapter.product.combination.update.default_combination_updater'] ?? $this->load('getPrestashop_Adapter_Product_Combination_Update_DefaultCombinationUpdaterService.php')));
