<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.stock.update.product_stock_updater' shared service.

return $this->services['prestashop.adapter.product.stock.update.product_stock_updater'] = new \PrestaShop\PrestaShop\Adapter\Product\Stock\Update\ProductStockUpdater(($this->services['prestashop.core.stock.stock_manager'] ?? ($this->services['prestashop.core.stock.stock_manager'] = new \PrestaShop\PrestaShop\Core\Stock\StockManager())), ($this->services['prestashop.adapter.product.repository.product_multi_shop_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductMultiShopRepositoryService.php')), ($this->services['prestashop.adapter.product.stock.repository.stock_available_multi_shop_repository'] ?? $this->load('getPrestashop_Adapter_Product_Stock_Repository_StockAvailableMultiShopRepositoryService.php')), ($this->services['prestashop.adapter.product.stock.repository.movement_reason_repository'] ?? $this->load('getPrestashop_Adapter_Product_Stock_Repository_MovementReasonRepositoryService.php')), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())));
