<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.bundle.routing.linter.admin_route_provider' shared service.

return $this->privates['prestashop.bundle.routing.linter.admin_route_provider'] = new \PrestaShopBundle\Routing\Linter\AdminRouteProvider(($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')));
