<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.customization.repository.customization_field_repository' shared service.

return $this->services['prestashop.adapter.product.customization.repository.customization_field_repository'] = new \PrestaShop\PrestaShop\Adapter\Product\Customization\Repository\CustomizationFieldRepository(($this->services['prestashop.adapter.product.customization.validate.customization_field_validator'] ?? ($this->services['prestashop.adapter.product.customization.validate.customization_field_validator'] = new \PrestaShop\PrestaShop\Adapter\Product\Customization\Validate\CustomizationFieldValidator())));
