<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.query_handler.search_products_for_association' shared service.

return $this->services['prestashop.adapter.product.query_handler.search_products_for_association'] = new \PrestaShop\PrestaShop\Adapter\Product\QueryHandler\SearchProductsForAssociationHandler(($this->services['prestashop.adapter.product.repository.product_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')), ($this->services['prestashop.adapter.product.image.product_image_url_factory'] ?? $this->load('getPrestashop_Adapter_Product_Image_ProductImageUrlFactoryService.php')));
