<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command_handler.update_product_type_handler' shared service.

return $this->services['prestashop.adapter.product.command_handler.update_product_type_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\UpdateProductTypeHandler(($this->services['prestashop.adapter.product.update.product_type_updater'] ?? $this->load('getPrestashop_Adapter_Product_Update_ProductTypeUpdaterService.php')));
