<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.specific_price.command_handler.delete_specific_price_handler' shared service.

return $this->services['prestashop.adapter.product.specific_price.command_handler.delete_specific_price_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\SpecificPrice\CommandHandler\DeleteSpecificPriceHandler(($this->services['prestashop.adapter.product.specific_price.repository.specific_price_repository'] ?? $this->load('getPrestashop_Adapter_Product_SpecificPrice_Repository_SpecificPriceRepositoryService.php')));
