<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product_general.configuration' shared service.

return $this->services['prestashop.adapter.product_general.configuration'] = new \PrestaShop\PrestaShop\Adapter\Product\GeneralConfiguration(($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.adapter.product.specific_price.update.specific_price_priority_updater'] ?? $this->load('getPrestashop_Adapter_Product_SpecificPrice_Update_SpecificPricePriorityUpdaterService.php')));
