<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.virtual_product.update.virtual_product_updater' shared service.

return $this->services['prestashop.adapter.product.virtual_product.update.virtual_product_updater'] = new \PrestaShop\PrestaShop\Adapter\Product\VirtualProduct\Update\VirtualProductUpdater(($this->services['prestashop.adapter.product.repository.product_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')), ($this->services['prestashop.adapter.file.uploader.virtual_product_file_uploader'] ?? $this->load('getPrestashop_Adapter_File_Uploader_VirtualProductFileUploaderService.php')), ($this->services['prestashop.adapter.product.virtual_product.repository.virtual_product_file_repository'] ?? $this->load('getPrestashop_Adapter_Product_VirtualProduct_Repository_VirtualProductFileRepositoryService.php')));
