<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.command_builder.combination.combination_commands_builder' shared service.

return $this->services['prestashop.core.form.command_builder.combination.combination_commands_builder'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\Combination\CombinationCommandsBuilder(new RewindableGenerator(function () {
    yield 0 => ($this->services['prestashop.core.form.command_builder.product.combination.stock_command_builder'] ?? ($this->services['prestashop.core.form.command_builder.product.combination.stock_command_builder'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\Combination\CombinationStockCommandsBuilder()));
    yield 1 => ($this->services['prestashop.core.form.command_builder.product.combination.price_command_builder'] ?? ($this->services['prestashop.core.form.command_builder.product.combination.price_command_builder'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\Combination\CombinationPriceCommandsBuilder()));
    yield 2 => ($this->services['prestashop.core.form.command_builder.product.combination.details_command_builder'] ?? ($this->services['prestashop.core.form.command_builder.product.combination.details_command_builder'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\Combination\CombinationDetailsCommandsBuilder()));
    yield 3 => ($this->services['prestashop.core.form.command_builder.product.combination.suppliers_command_builder'] ?? ($this->services['prestashop.core.form.command_builder.product.combination.suppliers_command_builder'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\Combination\CombinationSuppliersCommandsBuilder()));
    yield 4 => ($this->services['prestashop.core.form.command_builder.product.combination.images_command_builder'] ?? ($this->services['prestashop.core.form.command_builder.product.combination.images_command_builder'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\Combination\CombinationImagesCommandsBuilder()));
    yield 5 => ($this->services['prestashop.core.form.command_builder.product.combination.default_combination_commands_builder'] ?? ($this->services['prestashop.core.form.command_builder.product.combination.default_combination_commands_builder'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\Combination\DefaultCombinationCommandsBuilder()));
}, 6));
