<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.pricing.specific_price_type' shared service.

return $this->services['form.type.sell.product.pricing.specific_price_type'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Pricing\SpecificPriceType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getLanguages(), ($this->services['prestashop.adapter.form.choice_provider.combination_id_choice_provider'] ?? $this->load('getPrestashop_Adapter_Form_ChoiceProvider_CombinationIdChoiceProviderService.php')), ($this->services['prestashop.core.admin.url_generator'] ?? $this->load('getPrestashop_Core_Admin_UrlGeneratorService.php')), ($this->services['prestashop.adapter.product.repository.product_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')));
