<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.configure.advanced_parameters.profile' shared service.

return $this->services['form.type.configure.advanced_parameters.profile'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Profile\ProfileType(($this->services['translator'] ?? $this->getTranslatorService()));
