<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.product.warehouse_combination' shared service.

return $this->services['form.type.product.warehouse_combination'] = new \PrestaShopBundle\Form\Admin\Product\ProductWarehouseCombination(($this->services['translator'] ?? $this->getTranslatorService()));
