<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.identifiable_object.handler.form_handler_factory' shared service.

return $this->services['prestashop.core.form.identifiable_object.handler.form_handler_factory'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandlerFactory(($this->services['prestashop.core.hook.dispatcher'] ?? $this->getPrestashop_Core_Hook_DispatcherService()), ($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->get("_PS_MODE_DEMO_"));
