<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.image.product_image_filesystem_path_factory' shared service.

return $this->services['prestashop.adapter.product.image.product_image_filesystem_path_factory'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\ProductImagePathFactory((\dirname(__DIR__, 4).'/img/p/'), (\dirname(__DIR__, 4).'/img/tmp/'), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->language->iso_code);
