<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.service.product' shared service.

return $this->services['prestashop.service.product'] = new \PrestaShopBundle\Service\ProductService(($this->services['prestashop.adapter.data_provider.product'] ?? ($this->services['prestashop.adapter.data_provider.product'] = new \PrestaShop\PrestaShop\Adapter\Product\ProductDataProvider())));
