<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.util.color_brightness_calculator' shared service.

return $this->services['prestashop.core.util.color_brightness_calculator'] = new \PrestaShop\PrestaShop\Core\Util\ColorBrightnessCalculator();
