<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.shop.repository.shop_repository' shared service.

return $this->services['prestashop.adapter.shop.repository.shop_repository'] = new \PrestaShop\PrestaShop\Adapter\Shop\Repository\ShopRepository();
