<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.data.factory.order_decorator' shared service.

return $this->services['prestashop.core.grid.data.factory.order_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\OrderGridDataFactory(($this->services['prestashop.core.grid.data.factory.order'] ?? $this->load('getPrestashop_Core_Grid_Data_Factory_OrderService.php')), ($this->services['prestashop.core.localization.locale.repository'] ?? $this->getPrestashop_Core_Localization_Locale_RepositoryService()), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->language->getLocale());
