<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.image.repository.product_image_repository' shared service.

return $this->services['prestashop.adapter.product.image.repository.product_image_repository'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\Repository\ProductImageRepository(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'ps_', ($this->services['prestashop.adapter.product.image.validate.product_image_validator'] ?? ($this->services['prestashop.adapter.product.image.validate.product_image_validator'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\Validate\ProductImageValidator())), ($this->services['prestashop.adapter.product.image.product_image_url_factory'] ?? $this->load('getPrestashop_Adapter_Product_Image_ProductImageUrlFactoryService.php')), ($this->services['prestashop.adapter.product.combination.repository.combination_repository'] ?? $this->load('getPrestashop_Adapter_Product_Combination_Repository_CombinationRepositoryService.php')));
