<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.admin.controller.attribute_generator' shared service.

return $this->services['prestashop.adapter.admin.controller.attribute_generator'] = new \PrestaShop\PrestaShop\Adapter\Attribute\AdminAttributeGeneratorControllerWrapper();
