<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.supplier.command_handler.update_product_suppliers_handler' shared service.

return $this->services['prestashop.adapter.product.supplier.command_handler.update_product_suppliers_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Supplier\CommandHandler\UpdateProductSuppliersHandler(($this->services['prestashop.adapter.product.update.product_supplier_updater'] ?? $this->load('getPrestashop_Adapter_Product_Update_ProductSupplierUpdaterService.php')), ($this->services['prestashop.adapter.product.repository.product_supplier_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductSupplierRepositoryService.php')));
