<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.pack.update.product_pack_updater' shared service.

return $this->services['prestashop.adapter.product.pack.update.product_pack_updater'] = new \PrestaShop\PrestaShop\Adapter\Product\Pack\Update\ProductPackUpdater(($this->services['prestashop.adapter.product.repository.product_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')), ($this->services['prestashop.adapter.product.pack.repository.product_pack_repository'] ?? $this->load('getPrestashop_Adapter_Product_Pack_Repository_ProductPackRepositoryService.php')));
