<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bridge.admin_controller.legacy_controller_bridge_factory' shared service.

return $this->services['prestashop.bridge.admin_controller.legacy_controller_bridge_factory'] = new \PrestaShopBundle\Bridge\AdminController\LegacyControllerBridgeFactory(($this->services['prestashop.adapter.multistore_feature'] ?? $this->load('getPrestashop_Adapter_MultistoreFeatureService.php')), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService()), ($this->services['prestashop.core.hook.dispatcher'] ?? $this->getPrestashop_Core_Hook_DispatcherService()));
