<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.meta.command_handler.save_meta' shared service.

return $this->services['prestashop.adapter.meta.command_handler.save_meta'] = new \PrestaShop\PrestaShop\Adapter\Meta\CommandHandler\AddMetaHandler(($this->services['prestashop.core.hook.dispatcher'] ?? $this->getPrestashop_Core_Hook_DispatcherService()), ($this->services['validator'] ?? $this->load('getValidatorService.php')), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->get("PS_LANG_DEFAULT"), ($this->services['prestashop.adapter.meta.data_provider'] ?? ($this->services['prestashop.adapter.meta.data_provider'] = new \PrestaShop\PrestaShop\Adapter\Meta\MetaDataProvider())));
