<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.specific_price.query_handler.get_specific_price_list_handler' shared service.

return $this->services['prestashop.adapter.product.specific_price.query_handler.get_specific_price_list_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\SpecificPrice\QueryHandler\GetSpecificPriceListHandler(($this->services['prestashop.adapter.product.specific_price.repository.specific_price_repository'] ?? $this->load('getPrestashop_Adapter_Product_SpecificPrice_Repository_SpecificPriceRepositoryService.php')), ($this->services['prestashop.adapter.attribute.repository.attribute_repository'] ?? $this->load('getPrestashop_Adapter_Attribute_Repository_AttributeRepositoryService.php')), ($this->services['prestashop.core.product.combination.name_builder.combination_name_builder'] ?? $this->load('getPrestashop_Core_Product_Combination_NameBuilder_CombinationNameBuilderService.php')));
