<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.twig.extension.context_iso_code_provider_extension' shared service.

$this->services['prestashop.twig.extension.context_iso_code_provider_extension'] = $instance = new \PrestaShopBundle\Twig\ContextIsoCodeProviderExtension(((($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->language) ? (($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->language->iso_code) : ("en")));

$instance->logger = ($this->services['logger'] ?? $this->getLoggerService());
$instance->translator = ($this->services['translator'] ?? $this->getTranslatorService());

return $instance;
