<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.update.product_type_updater' shared service.

return $this->services['prestashop.adapter.product.update.product_type_updater'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\ProductTypeUpdater(($this->services['prestashop.adapter.product.repository.product_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')), ($this->services['prestashop.adapter.product.pack.update.product_pack_updater'] ?? $this->load('getPrestashop_Adapter_Product_Pack_Update_ProductPackUpdaterService.php')), ($this->services['prestashop.adapter.product.combination.update.combination_deleter'] ?? $this->load('getPrestashop_Adapter_Product_Combination_Update_CombinationDeleterService.php')), ($this->services['prestashop.adapter.product.virtual_product.update.virtual_product_updater'] ?? $this->load('getPrestashop_Adapter_Product_VirtualProduct_Update_VirtualProductUpdaterService.php')), ($this->services['prestashop.adapter.product.stock.update.product_stock_updater'] ?? $this->load('getPrestashop_Adapter_Product_Stock_Update_ProductStockUpdaterService.php')), ($this->services['prestashop.adapter.product.pack.repository.product_pack_repository'] ?? $this->load('getPrestashop_Adapter_Product_Pack_Repository_ProductPackRepositoryService.php')));
