<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.category.repository.category_preview_repository' shared service.

return $this->services['prestashop.adapter.category.repository.category_preview_repository'] = new \PrestaShop\PrestaShop\Adapter\Category\Repository\CategoryPreviewRepository(($this->services['prestashop.adapter.category.repository.category_repository'] ?? $this->load('getPrestashop_Adapter_Category_Repository_CategoryRepositoryService.php')), ($this->services['prestashop.adapter.image.category_image_path_factory'] ?? $this->load('getPrestashop_Adapter_Image_CategoryImagePathFactoryService.php')));
