<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.feature_value.command_handler.set_product_feature_values_handler' shared service.

return $this->services['prestashop.adapter.product.feature_value.command_handler.set_product_feature_values_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\FeatureValue\CommandHandler\SetProductFeatureValuesHandler(($this->services['prestashop.adapter.product.feature_value.update.product_feature_value_updater'] ?? $this->load('getPrestashop_Adapter_Product_FeatureValue_Update_ProductFeatureValueUpdaterService.php')));
