<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.command_handler.generate_product_combinations_handler' shared service.

return $this->services['prestashop.adapter.product.combination.command_handler.generate_product_combinations_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\CommandHandler\GenerateProductCombinationsHandler(($this->services['prestashop.adapter.product.combination.create.combination_creator'] ?? $this->load('getPrestashop_Adapter_Product_Combination_Create_CombinationCreatorService.php')), ($this->services['prestashop.adapter.product.update.product_supplier_updater'] ?? $this->load('getPrestashop_Adapter_Product_Update_ProductSupplierUpdaterService.php')));
