<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.customization.command_handler.set_product_customization_fields_handler' shared service.

return $this->services['prestashop.adapter.product.customization.command_handler.set_product_customization_fields_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Customization\CommandHandler\SetProductCustomizationFieldsHandler(($this->services['prestashop.adapter.product.repository.product_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')), ($this->services['prestashop.adapter.product.customization.update.product_customization_field_updater'] ?? $this->load('getPrestashop_Adapter_Product_Customization_Update_ProductCustomizationFieldUpdaterService.php')));
