<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.product.combination_bulk' shared service.

return $this->services['form.type.product.combination_bulk'] = new \PrestaShopBundle\Form\Admin\Product\ProductCombinationBulk(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())));
