<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.international.tax_options' shared service.

return $this->services['form.type.international.tax_options'] = new \PrestaShopBundle\Form\Admin\Improve\International\Tax\TaxOptionsType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getLanguages(), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->getBoolean("PS_USE_ECOTAX"), ($this->services['prestashop.core.form.choice_provider.tax_address_type_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_TaxAddressTypeChoiceProviderService.php')), ($this->services['prestashop.core.form.choice_provider.tax_rule_group_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_TaxRuleGroupChoiceProviderService.php')));
