<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.contact' shared service.

return $this->services['form.type.contact'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\Contact\ContactType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getLanguages(), ($this->services['prestashop.bundle.form.data_transformer.default_language_to_filled_array'] ?? $this->load('getPrestashop_Bundle_Form_DataTransformer_DefaultLanguageToFilledArrayService.php')), ($this->services['prestashop.adapter.multistore_feature'] ?? $this->load('getPrestashop_Adapter_MultistoreFeatureService.php'))->isUsed());
