<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.webservice.webservice_key_type' shared service.

return $this->services['form.type.webservice.webservice_key_type'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Webservice\WebserviceKeyType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getLanguages(), ($this->services['prestashop.adapter.multistore_feature'] ?? $this->load('getPrestashop_Adapter_MultistoreFeatureService.php'))->isUsed(), ($this->services['prestashop.adapter.form.choice_provider.resources_choice_provider'] ?? ($this->services['prestashop.adapter.form.choice_provider.resources_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ResourcesChoiceProvider()))->getChoices(), ($this->services['prestashop.core.form.choice_provider.permissions_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_PermissionsChoiceProviderService.php'))->getChoices());
