<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.definition.factory.product_light' shared service.

$this->services['prestashop.core.grid.definition.factory.product_light'] = $instance = new \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ProductLightGridDefinitionFactory(($this->services['prestashop.core.hook.dispatcher'] ?? $this->getPrestashop_Core_Hook_DispatcherService()), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())));

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
