<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bridge.helper.listing.helper_list_configurator' shared service.

return $this->services['prestashop.bridge.helper.listing.helper_list_configurator'] = new \PrestaShopBundle\Bridge\Helper\Listing\HelperListConfigurator(($this->services['prestashop.bridge.smarty.breadcrumbs_and_title_configurator'] ?? $this->load('getPrestashop_Bridge_Smarty_BreadcrumbsAndTitleConfiguratorService.php')));
