<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.admin.wrapper.product' shared service.

return $this->services['prestashop.adapter.admin.wrapper.product'] = new \PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->employee->getAssociatedShops(), ($this->services['prestashop.core.localization.locale.context_locale'] ?? $this->load('getPrestashop_Core_Localization_Locale_ContextLocaleService.php')), ($this->services['prestashop.utils.float_parser'] ?? $this->load('getPrestashop_Utils_FloatParserService.php')));
