<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.command_handler.set_default_combination_handler' shared service.

return $this->services['prestashop.adapter.product.combination.command_handler.set_default_combination_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\CommandHandler\SetDefaultCombinationHandler(($this->services['prestashop.adapter.product.combination.update.default_combination_updater'] ?? $this->load('getPrestashop_Adapter_Product_Combination_Update_DefaultCombinationUpdaterService.php')));
