<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.definition.factory.customer' shared service.

$this->services['prestashop.core.grid.definition.factory.customer'] = $instance = new \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CustomerGridDefinitionFactory(($this->services['prestashop.core.hook.dispatcher'] ?? $this->getPrestashop_Core_Hook_DispatcherService()), ($this->services['prestashop.core.b2b.b2b_feature'] ?? $this->load('getPrestashop_Core_B2b_B2bFeatureService.php'))->isActive(), ($this->services['prestashop.adapter.multistore_feature'] ?? $this->load('getPrestashop_Adapter_MultistoreFeatureService.php'))->isActive(), ($this->services['prestashop.adapter.form.choice_provider.gender_by_id_choice_provider'] ?? ($this->services['prestashop.adapter.form.choice_provider.gender_by_id_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\GenderByIdChoiceProvider()))->getChoices(), ($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->language->date_format_full, ($this->services['prestashop.adapter.feature.group_feature'] ?? $this->load('getPrestashop_Adapter_Feature_GroupFeatureService.php'))->isActive(), ($this->services['prestashop.adapter.form.choice_provider.group_by_id_choice_provider'] ?? $this->load('getPrestashop_Adapter_Form_ChoiceProvider_GroupByIdChoiceProviderService.php'))->getChoices());

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
