<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.image.command_handler.add_product_image_handler' shared service.

return $this->services['prestashop.adapter.product.image.command_handler.add_product_image_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\CommandHandler\AddProductImageHandler(($this->services['prestashop.adapter.product.image.uploader.product_image_uploader'] ?? $this->load('getPrestashop_Adapter_Product_Image_Uploader_ProductImageUploaderService.php')), ($this->services['prestashop.adapter.product.image.repository.product_image_repository'] ?? $this->load('getPrestashop_Adapter_Product_Image_Repository_ProductImageRepositoryService.php')), ($this->services['prestashop.adapter.image.image_validator'] ?? $this->load('getPrestashop_Adapter_Image_ImageValidatorService.php')), ($this->services['prestashop.adapter.shop.context'] ?? ($this->services['prestashop.adapter.shop.context'] = new \PrestaShop\PrestaShop\Adapter\Shop\Context()))->getContextListShopID());
