<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.file.uploader.virtual_product_file_uploader' shared service.

return $this->services['prestashop.adapter.file.uploader.virtual_product_file_uploader'] = new \PrestaShop\PrestaShop\Adapter\File\Uploader\VirtualProductFileUploader(($this->services['prestashop.adapter.file.validator.virtual_product_file_validator'] ?? $this->load('getPrestashop_Adapter_File_Validator_VirtualProductFileValidatorService.php')), (\dirname(__DIR__, 4).'/download/'));
