<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.specific_price.query_handler.get_specific_price_for_editing_handler' shared service.

return $this->services['prestashop.adapter.product.specific_price.query_handler.get_specific_price_for_editing_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\SpecificPrice\QueryHandler\GetSpecificPriceForEditingHandler(($this->services['prestashop.adapter.product.specific_price.repository.specific_price_repository'] ?? $this->load('getPrestashop_Adapter_Product_SpecificPrice_Repository_SpecificPriceRepositoryService.php')), ($this->services['prestashop.adapter.customer.repository.customer_repository'] ?? ($this->services['prestashop.adapter.customer.repository.customer_repository'] = new \PrestaShop\PrestaShop\Adapter\Customer\Repository\CustomerRepository())));
