<?php exit;?>
array (
  'FlatBBeditorstate' => true,
  'font_size' => true,
  'font_color' => true,
  'bold' => true,
  'italic' => true,
  'underline' => true,
  'strike' => true,
  'code' => true,
  'quote' => true,
  'hide' => true,
  'align_center' => true,
  'align_right' => true,
  'insert_picture_width' => true,
  'insert_picture' => true,
  'insert_link' => true,
  'insert_youtube_video' => true,
  'insert_dailymotion_video' => true,
  'insert_video' => true,
  'upload_picture' => true,
  'fullscreen_editor' => true,
)