<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXofCI1Q\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXofCI1Q/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXofCI1Q.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXofCI1Q\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerXofCI1Q\appAppKernelDevDebugContainer([
    'container.build_hash' => 'XofCI1Q',
    'container.build_id' => '80ae5f7f',
    'container.build_time' => 1680250387,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXofCI1Q');
